version: '3.8'
services: 
    api-service:
        build: .
        volumes:
          - type: bind
            source: ./src
            target: /src
        ports:
          - 8080:8080
        environment: 
            FLASK_DEBUG: 1
            MONGO_URI: mongodb://mongodb:27017/gallery
            AWS_ACCESS_KEY: AKIA2U3H5ZR6USQP6CUW
            AWS_SECRET_KEY: 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
        depends_on:
          - mongodb
        links:  
          - mongodb
    mongodb:
        image: mongo
        ports:
          - 27017:27017
        volumes: 
          - /data/db

    